// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQxM3zJHi8LZjj-W4QD4LB7IgmcgjaZM',
    appId: '1:387537499798:web:8f7f4c57f85f072b5934b7',
    messagingSenderId: '387537499798',
    projectId: 'euphoric-coast-384514',
    authDomain: 'euphoric-coast-384514.firebaseapp.com',
    databaseURL: 'https://euphoric-coast-384514-default-rtdb.firebaseio.com',
    storageBucket: 'euphoric-coast-384514.appspot.com',
    measurementId: 'G-KM94H0KXHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfN0MN1eMuyoBNFNaiBawiBLgfXZYzdOM',
    appId: '1:387537499798:android:eee3f4d8744a534f5934b7',
    messagingSenderId: '387537499798',
    projectId: 'euphoric-coast-384514',
    databaseURL: 'https://euphoric-coast-384514-default-rtdb.firebaseio.com',
    storageBucket: 'euphoric-coast-384514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBweixzFE4754LYWxboj_0ImuunCjgMo',
    appId: '1:387537499798:ios:0123b920b6132d2d5934b7',
    messagingSenderId: '387537499798',
    projectId: 'euphoric-coast-384514',
    databaseURL: 'https://euphoric-coast-384514-default-rtdb.firebaseio.com',
    storageBucket: 'euphoric-coast-384514.appspot.com',
    iosBundleId: 'com.example.seva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTBweixzFE4754LYWxboj_0ImuunCjgMo',
    appId: '1:387537499798:ios:0123b920b6132d2d5934b7',
    messagingSenderId: '387537499798',
    projectId: 'euphoric-coast-384514',
    databaseURL: 'https://euphoric-coast-384514-default-rtdb.firebaseio.com',
    storageBucket: 'euphoric-coast-384514.appspot.com',
    iosBundleId: 'com.example.seva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC8MRCIjicTAgYN5ppp3IpWM_zj1zzQa8',
    appId: '1:387537499798:web:0248faa072a24bce5934b7',
    messagingSenderId: '387537499798',
    projectId: 'euphoric-coast-384514',
    authDomain: 'euphoric-coast-384514.firebaseapp.com',
    databaseURL: 'https://euphoric-coast-384514-default-rtdb.firebaseio.com',
    storageBucket: 'euphoric-coast-384514.appspot.com',
    measurementId: 'G-1ZL4X7L19M',
  );
}
